import GoogleAnalytics from "@/lib/GoogleAnalytics";
import "./globals.css";
import Footer from "@/components/footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleAnalytics GA_MEASUREMENT_ID="G-JL3149DC93" />
      <body>{children}</body>
      <Footer />
    </html>
  );
}
